=== Aitam1/Juego-de-granja/datos.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

                            <!-- ELEMENTO RAIZ -->
    <xs:element name = "granja">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref = "semillas" minOccurs="1" maxOccurs="1"></xs:element>
                <xs:element ref = "herramientas" minOccurs="1" maxOccurs="1"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

<!-- =================== SECCION DE SEMILLAS =================== -->
    <xs:element name = "semillas">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref = "semilla" minOccurs = "1" maxOccurs = "unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name = "semilla">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref = "nombre" minOccurs = "1" maxOccurs = "1"></xs:element>
                <xs:element ref = "emoji" minOccurs = "1" maxOccurs = "1"></xs:element>
                <xs:element ref = "precioCompra" minOccurs = "1" maxOccurs = "1"></xs:element>
                <xs:element ref = "precioVenta" minOccurs = "1" maxOccurs = "1"></xs:element>
                <xs:element ref = "tiempoMaduracion" minOccurs = "1" maxOccurs = "1"></xs:element>
            </xs:sequence>
            <xs:attribute ref = "idSemilla"></xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name = "nombre" type = "xs:string"></xs:element>

    <xs:element name = "emoji" type = "xs:string"></xs:element>

    <xs:element name = "precioCompra">
        <xs:simpleType>
            <xs:restriction base = "xs:int">
                <xs:pattern value = "[0-9]+"></xs:pattern>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name = "precioVenta">
        <xs:simpleType>
            <xs:restriction base = "xs:int">
                <xs:pattern value = "[0-9]+"></xs:pattern>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name = "tiempoMaduracion">
        <xs:simpleType>
            <xs:restriction base = "xs:int">
                <xs:pattern value = "[0-9]+"></xs:pattern>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>



<!-- =================== SECCION DE HERRAMIENTAS =================== -->
    <xs:element name = "herramientas">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref = "herramienta" minOccurs = "1" maxOccurs = "unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name = "herramienta">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref = "nombreH" minOccurs = "1" maxOccurs = "1"></xs:element>
                <xs:element ref = "emojiH" minOccurs = "1" maxOccurs = "1"></xs:element>
                <xs:element ref = "tipoEfecto" minOccurs = "1" maxOccurs = "1"></xs:element>

                <xs:element ref = "niveles" minOccurs="1" maxOccurs="1"></xs:element>
            </xs:sequence>
            <xs:attribute ref = "idHerramienta"></xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name = "nombreH" type = "xs:string"></xs:element>

    <xs:element name = "emojiH" type = "xs:string"></xs:element>

    <xs:element name = "tipoEfecto" type = "xs:string"></xs:element>

    <xs:element name = "niveles">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref = "nivel" minOccurs = "1" maxOccurs = "unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name = "nivel">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref = "nombreNivel" minOccurs = "1" maxOccurs = "1"></xs:element>
                <xs:element ref = "costo" minOccurs = "1" maxOccurs = "1"></xs:element>
                <xs:element ref = "efecto" minOccurs = "1" maxOccurs = "1"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name = "nombreNivel" type = "xs:string"></xs:element>

    <xs:element name = "costo">
        <xs:simpleType>
            <xs:restriction base = "xs:int">
                <xs:pattern value = "[0-9]{1,3}"></xs:pattern>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name = "efecto">
        <xs:simpleType>
            <xs:restriction base = "xs:decimal">
                <xs:pattern value = "[0-9]\.[0-9]+"></xs:pattern>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

                            <!-- ATRIBUTOS -->
    <!-- SECCION DE SEMILLAS -->
    <xs:attribute name = "idSemilla">
        <xs:simpleType>
            <xs:restriction base = "xs:ID">
                <xs:pattern value = "s[0-9]+"></xs:pattern>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <!-- SECCION DE HERRAMIENTAS -->
    <xs:attribute name = "idHerramienta">
        <xs:simpleType>
            <xs:restriction base = "xs:ID">
                <xs:pattern value = "h[0-9]+"></xs:pattern>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>


</xs:schema>

=== Aitam1/Juego-de-granja/datos.xml
<?xml version="1.0" encoding="UTF-8"?>

<granja xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datos.xsd">
    

    <!-- LAS SEMILLAS -->
    <semillas>

        <semilla idSemilla = "s1">
            <nombre>Trigo</nombre>
            <emoji>🌾</emoji>
            <precioCompra>10</precioCompra>
            <precioVenta>25</precioVenta>
            <tiempoMaduracion>10</tiempoMaduracion>
        </semilla>

        <semilla idSemilla = "s2">
            <nombre>Zanahoria</nombre>
            <emoji>🥕</emoji>
            <precioCompra>15</precioCompra>
            <precioVenta>35</precioVenta>
            <tiempoMaduracion>15</tiempoMaduracion>
        </semilla>

        <semilla idSemilla = "s3">
            <nombre>Tomate</nombre>
            <emoji>🍅</emoji>
            <precioCompra>20</precioCompra>
            <precioVenta>50</precioVenta>
            <tiempoMaduracion>20</tiempoMaduracion>
        </semilla>

        <semilla idSemilla = "s4">
            <nombre>Maíz</nombre>
            <emoji>🌽</emoji>
            <precioCompra>25</precioCompra>
            <precioVenta>65</precioVenta>
            <tiempoMaduracion>25</tiempoMaduracion>
        </semilla>

        <semilla idSemilla = "s5">
            <nombre>Kiwi</nombre>
            <emoji>🥝</emoji>
            <precioCompra>30</precioCompra>
            <precioVenta>80</precioVenta>
            <tiempoMaduracion>30</tiempoMaduracion>
        </semilla>

    </semillas>


    <!-- LAS HERRAMIENTAS-->
    <herramientas>

        <herramienta idHerramienta = "h1">
            <nombreH>Azada</nombreH>
            <emojiH>🪓</emojiH>
            <tipoEfecto>multiplica el precio de venta al cosechar</tipoEfecto>
            <niveles>
                <nivel>
                    <nombreNivel>Basica</nombreNivel>
                    <costo>0</costo>
                    <efecto>1.0</efecto>
                </nivel>

                <nivel>
                    <nombreNivel>Mejorada</nombreNivel>
                    <costo>80</costo>
                    <efecto>1.3</efecto>
                </nivel>

                <nivel>
                    <nombreNivel>Maestra</nombreNivel>
                    <costo>200</costo>
                    <efecto>1.6</efecto>
                </nivel>
            </niveles>
        </herramienta>


        <herramienta idHerramienta = "h2">
            <nombreH>Regadera</nombreH>
            <emojiH>🪣</emojiH>
            <tipoEfecto>reduce el tiempo de maduracion de las plantas</tipoEfecto>
            <niveles>
                <nivel>
                    <nombreNivel>Basica</nombreNivel>
                    <costo>0</costo>
                    <efecto>1.0</efecto>
                </nivel>

                <nivel>
                    <nombreNivel>Mejorada</nombreNivel>
                    <costo>80</costo>
                    <efecto>0.7</efecto>
                </nivel>

                <nivel>
                    <nombreNivel>Maestra</nombreNivel>
                    <costo>200</costo>
                    <efecto>0.5</efecto>
                </nivel>
            </niveles>
        </herramienta>


        <herramienta idHerramienta = "h3">
            <nombreH>Hoz</nombreH>
            <emojiH>🌙</emojiH>
            <tipoEfecto>multiplica los frutos obtenidos al cosechar</tipoEfecto>
            <niveles>
                <nivel>
                    <nombreNivel>Basica</nombreNivel>
                    <costo>0</costo>
                    <efecto>1.0</efecto>
                </nivel>

                <nivel>
                    <nombreNivel>Mejorada</nombreNivel>
                    <costo>80</costo>
                    <efecto>1.3</efecto>
                </nivel>

                <nivel>
                    <nombreNivel>Maestra</nombreNivel>
                    <costo>200</costo>
                    <efecto>1.6</efecto>
                </nivel>
            </niveles>
        </herramienta>

    </herramientas>

</granja>
